// PROJECTS
export const SET_PAGES = 'SET_PAGES'
export const SET_PAGES2 = 'SET_PAGES2'
export const SET_PAGES3 = 'SET_PAGES3'
export const PAGE_FETCHED = 'PAGE_FETCHED'
export const CHILD_PAGE_FETCHED = 'CHILD_PAGE_FETCHED'

