// PROJECTS
export const SET_FIRST_LEVEL_PAGES = 'SET_FIRST_LEVEL_PAGES'
export const FIRST_LEVEL_PAGE_FETCHED = 'FIRST_LEVEL_PAGE_FETCHED'
export const SECOND_LEVEL_PAGE_FETCHED = 'SECOND_LEVEL_PAGE_FETCHED'

